apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-ms
  template:
    metadata:
      labels:
        app: inventario-ms
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: inventario-ms
          image: danttee/inventario-ms:latest
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: inventario-ms
spec:
  selector:
    app: inventario-ms
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP